using Xkb.Native;

namespace Xkb;

/// <summary>Flags for creating an <see cref="XkbContext"/>.</summary>
[Flags]
public enum XkbContextFlags : uint
{
    /// <summary>Do not apply any flags.</summary>
    None = xkb_context_flags.XKB_CONTEXT_NO_FLAGS,

    /// <summary>Create the context with an empty include path.</summary>
    NoDefaultIncludes = xkb_context_flags.XKB_CONTEXT_NO_DEFAULT_INCLUDES,

    /// <summary>
    /// Don't take RMLVO names or include-path roots from the environment
    /// (XKB_DEFAULT_RULES, XKB_CONFIG_ROOT, HOME, XDG_CONFIG_DIR, ...).
    /// </summary>
    NoEnvironmentNames = xkb_context_flags.XKB_CONTEXT_NO_ENVIRONMENT_NAMES,

    /// <summary>Use getenv() instead of secure_getenv() to read environment variables.</summary>
    NoSecureGetenv = xkb_context_flags.XKB_CONTEXT_NO_SECURE_GETENV,
}

/// <summary>The text format of a serialized keymap.</summary>
public enum XkbKeymapFormat : uint
{
    /// <summary>The classic XKB text format, as generated by xkbcomp -xkb.</summary>
    TextV1 = xkb_keymap_format.XKB_KEYMAP_FORMAT_TEXT_V1,

    /// <summary>The XKB text format v2 (xkbcommon 1.8+).</summary>
    TextV2 = xkb_keymap_format.XKB_KEYMAP_FORMAT_TEXT_V2,

    /// <summary>
    /// When serializing, use the format the keymap was originally compiled from.
    /// </summary>
    UseOriginalFormat = 0xffffffff,
}

/// <summary>Direction of a key press event fed to <see cref="XkbState.UpdateKey"/>.</summary>
public enum XkbKeyDirection : uint
{
    /// <summary>The key was released.</summary>
    Up = xkb_key_direction.XKB_KEY_UP,

    /// <summary>The key was pressed.</summary>
    Down = xkb_key_direction.XKB_KEY_DOWN,
}

/// <summary>Modifier and layout component masks of an <see cref="XkbState"/>.</summary>
[Flags]
public enum XkbStateComponent : uint
{
    /// <summary>Depressed modifiers, i.e. currently pressed and affecting the state.</summary>
    ModsDepressed = xkb_state_component.XKB_STATE_MODS_DEPRESSED,

    /// <summary>Latched modifiers, i.e. affecting the next key press only.</summary>
    ModsLatched = xkb_state_component.XKB_STATE_MODS_LATCHED,

    /// <summary>Locked modifiers, i.e. affecting keys until explicitly unlocked.</summary>
    ModsLocked = xkb_state_component.XKB_STATE_MODS_LOCKED,

    /// <summary>Effective modifiers: the combination of depressed, latched and locked.</summary>
    ModsEffective = xkb_state_component.XKB_STATE_MODS_EFFECTIVE,

    /// <summary>Depressed layout.</summary>
    LayoutDepressed = xkb_state_component.XKB_STATE_LAYOUT_DEPRESSED,

    /// <summary>Latched layout.</summary>
    LayoutLatched = xkb_state_component.XKB_STATE_LAYOUT_LATCHED,

    /// <summary>Locked layout.</summary>
    LayoutLocked = xkb_state_component.XKB_STATE_LAYOUT_LOCKED,

    /// <summary>Effective layout: the combination of depressed, latched and locked.</summary>
    LayoutEffective = xkb_state_component.XKB_STATE_LAYOUT_EFFECTIVE,

    /// <summary>LEDs (derived from the other state components).</summary>
    Leds = xkb_state_component.XKB_STATE_LEDS,
}

/// <summary>Match flags for modifier matching.</summary>
[Flags]
public enum XkbStateMatch : uint
{
    /// <summary>Any of the given modifiers must be active.</summary>
    Any = xkb_state_match.XKB_STATE_MATCH_ANY,

    /// <summary>All of the given modifiers must be active.</summary>
    All = xkb_state_match.XKB_STATE_MATCH_ALL,

    /// <summary>Allow active modifiers not specified in the arguments.</summary>
    NonExclusive = xkb_state_match.XKB_STATE_MATCH_NON_EXCLUSIVE,
}

/// <summary>Modes for calculating consumed modifiers.</summary>
public enum XkbConsumedMode : uint
{
    /// <summary>The mode defined by the XKB specification.</summary>
    Xkb = xkb_consumed_mode.XKB_CONSUMED_MODE_XKB,

    /// <summary>The mode used by the GTK toolkit.</summary>
    Gtk = xkb_consumed_mode.XKB_CONSUMED_MODE_GTK,
}

/// <summary>Status of an <see cref="XkbComposeState"/>.</summary>
public enum XkbComposeStatus : uint
{
    /// <summary>The initial state; no sequence is in progress.</summary>
    Nothing = xkb_compose_status.XKB_COMPOSE_NOTHING,

    /// <summary>In the middle of a sequence.</summary>
    Composing = xkb_compose_status.XKB_COMPOSE_COMPOSING,

    /// <summary>A complete sequence has been matched.</summary>
    Composed = xkb_compose_status.XKB_COMPOSE_COMPOSED,

    /// <summary>The last sequence was cancelled due to an unmatched keysym.</summary>
    Cancelled = xkb_compose_status.XKB_COMPOSE_CANCELLED,
}

/// <summary>The effect of a keysym fed to <see cref="XkbComposeState.Feed"/>.</summary>
public enum XkbComposeFeedResult : uint
{
    /// <summary>The keysym had no effect — it did not affect the status.</summary>
    Ignored = xkb_compose_feed_result.XKB_COMPOSE_FEED_IGNORED,

    /// <summary>The keysym started, advanced, cancelled or finished a sequence.</summary>
    Accepted = xkb_compose_feed_result.XKB_COMPOSE_FEED_ACCEPTED,
}

/// <summary>xkbcommon log levels, mirroring syslog priorities.</summary>
public enum XkbLogLevel : uint
{
    /// <summary>Log critical internal errors only.</summary>
    Critical = xkb_log_level.XKB_LOG_LEVEL_CRITICAL,

    /// <summary>Log all errors.</summary>
    Error = xkb_log_level.XKB_LOG_LEVEL_ERROR,

    /// <summary>Log warnings and errors.</summary>
    Warning = xkb_log_level.XKB_LOG_LEVEL_WARNING,

    /// <summary>Log information, warnings and errors.</summary>
    Info = xkb_log_level.XKB_LOG_LEVEL_INFO,

    /// <summary>Log everything.</summary>
    Debug = xkb_log_level.XKB_LOG_LEVEL_DEBUG,
}

/// <summary>Flags for creating an <see cref="XkbRegistry"/>.</summary>
[Flags]
public enum XkbRegistryFlags : uint
{
    /// <summary>Do not apply any flags.</summary>
    None = rxkb_context_flags.RXKB_CONTEXT_NO_FLAGS,

    /// <summary>
    /// Skip the default include paths; the caller must append include paths
    /// before parsing.
    /// </summary>
    NoDefaultIncludes = rxkb_context_flags.RXKB_CONTEXT_NO_DEFAULT_INCLUDES,

    /// <summary>Load the exotic (extras) rulesets in addition to the default ones.</summary>
    LoadExoticRules = rxkb_context_flags.RXKB_CONTEXT_LOAD_EXOTIC_RULES,

    /// <summary>Use getenv() instead of secure_getenv() to read environment variables.</summary>
    NoSecureGetenv = rxkb_context_flags.RXKB_CONTEXT_NO_SECURE_GETENV,
}

/// <summary>Popularity of a registry item.</summary>
public enum XkbPopularity : uint
{
    /// <summary>The item is from the standard ruleset distribution.</summary>
    Standard = rxkb_popularity.RXKB_POPULARITY_STANDARD,

    /// <summary>The item is from the exotic (extras) ruleset distribution.</summary>
    Exotic = rxkb_popularity.RXKB_POPULARITY_EXOTIC,
}
